---
#- name: rsync lt_tools directory to target
#  synchronize:
#      src: ~/lt_tools
#      dest: "{{ ansible_user_dir }}/lt_tools"
#      archive: yes
#      group: no
#      owner: no

- name: rsync lt_tools directory to target
  shell: "rsync -Faz --no-owner --no-group --stats ~/lt_tools/ {{ lt_user }}@{{ inventory_hostname }}:{{ ansible_user_dir }}/lt_tools/ | awk '/files transferred/ {print $5}'"
  delegate_to: 127.0.0.1
  register: rsync_result
  changed_when: rsync_result.stdout != '0'

#- debug: var=rsync_result
