---
- name: have tmux (Debians)
  remote_user: root
  apt: name={{ item }} state=present
  with_items:
      - tmux
  when: ansible_os_family == "Debian"

- name: have tmux (RedHats)
  remote_user: root
  yum: name={{ item }} state=present
  with_items:
      - tmux
  when: ansible_os_family == "RedHat"

- name: have tmux (OSX)
  homebrew: name=tmux update_homebrew=yes
  when: ansible_os_family == "Darwin"


- name: have dotfile (lt_user)
  template: src=tmux.conf.j2 dest=~/.tmux.conf backup=yes
